services:
  db:
    container_name: prueba_node
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "123" 
      MYSQL_DATABASE: db_prueba_node
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql